### ISSUE TITLE
Provide most common decoders in package. Msgpack decoder

### ISSUE THREAD

**Issue by blitzarx1** [cswank/kcli#14]
@cswank I loved your project!

I used your protobuf example and created msgpack decoder. 

1. Is it worth adding it to decoder examples? 
2. Maybe you should consider to provide us with the most common decoders, and I could contribute with msgpack decoder?

What do you think? ([link to decoder itself](https://github.com/bl17zar/kcli-msgpack-decoder))

P.S. I put 100th star on your project ;)

**Comment by cswank** [comment]
Thanks a lot for the feedback!  I think it'd be great to add another decoder example, but I'm hesitant to add custom decoders as part of the lib because there are just too many possible versions of so many different possible encoding formats.  I'd rather just have more examples since the plugins are really easy to generate yourself.

I moved the protobuf example to make room for your upcoming PR (I suggest examples/plugins/msgpack).  Thanks!

**Comment by blitzarx1** [comment]
Good! I will make it on upcoming holidays. Merry x-mas XoXo :)

**Comment by blitzarx1** [comment]
created PR

**Comment by cswank** [comment]
Thanks a lot.  Happy new year to you.
